# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_organizer',
        ),
    ]
