# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0002_remove_userprofile_is_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
