# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0003_remove_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('dob', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('website_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('facebook_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('user_profile_information', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='eventify_api.UserProfileInformation')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('skill_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='users',
            name='user_skills',
            field=models.ManyToManyField(to='eventify_api.UserSkills'),
        ),
    ]
