# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0005_auto_20170117_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('event_start_time', models.DateTimeField()),
                ('event_end_time', models.DateTimeField()),
                ('entry_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              primary_key=True, serialize=False, to='eventify_api.Eventify_User')),
            ],
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              primary_key=True, serialize=False, to='eventify_api.Eventify_User')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventBooking',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='eventify_api.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ManyToManyField(to='eventify_api.Organiser'),
        ),
        migrations.AddField(
            model_name='event',
            name='panelist',
            field=models.ManyToManyField(to='eventify_api.Panelist'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='eventify_api.Event'),
        ),
    ]
