# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0006_auto_20170117_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_seat_capacity', models.IntegerField()),
                ('venue_latitude', models.DecimalField(
                    decimal_places=6, max_digits=9)),
                ('venue_longitude', models.DecimalField(
                    decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(
                default=123, on_delete=django.db.models.deletion.CASCADE, to='eventify_api.Venue'),
            preserve_default=False,
        ),
    ]
