# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-18 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0007_auto_20170117_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking',
            field=models.ManyToManyField(
                through='eventify_api.UserEventBooking', to='eventify_api.Eventify_User'),
        ),
        migrations.AddField(
            model_name='usereventbooking',
            name='booking_datetime',
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usereventbooking',
            name='booking_seat_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usereventbooking',
            name='event',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='eventify_api.Event'),
        ),
        migrations.AddField(
            model_name='usereventbooking',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='eventify_api.Eventify_User'),
        ),
    ]
