# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0010_auto_20170118_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventbooking',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='eventify_api.Event'),
        ),
        migrations.AlterField(
            model_name='usereventbooking',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='eventify_api.Eventify_User'),
        ),
    ]
