# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-18 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0013_auto_20170118_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment_id',
            new_name='attachment_url',
        ),
    ]
