# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0014_auto_20170118_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTalk',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_name', models.CharField(max_length=100)),
                ('talk_datetime', models.DateTimeField(
                    blank=True, default=datetime.datetime.now)),
                ('event', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='eventify_api.Event')),
            ],
        ),
    ]
