# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventify_api', '0015_eventtalk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='event',
        ),
        migrations.AddField(
            model_name='attachment',
            name='event_talk',
            field=models.ForeignKey(
                default=23, on_delete=django.db.models.deletion.CASCADE, to='eventify_api.EventTalk'),
            preserve_default=False,
        ),
    ]
